name: pcccs2dev
dependencies:
    - python=2.7.12
    - nose=1.3.7
    - pip:
        - pyparsing==2.2.0
        - toolz==0.8.2
        - git+https://github.com/jcrudy/clinvoc.git@18863293c528691b2c0be8ec500cb4b1f6695617